import { INPUT_TYPES } from "../../../constants.ts";
import { generateUniqueKey } from "../../../helpers/generateUniqueKey.ts";

export const formDetails = [
  {
    key: generateUniqueKey("firstName"),
    name: "firstName",
    label: "First Name",
    type: INPUT_TYPES.TEXT,
    required: true,
    xs: 12,
    sm: 12,
    md: 12,
  },
  {
    key: generateUniqueKey("lastName"),
    name: "lastName",
    label: "Last Name",
    type: INPUT_TYPES.TEXT,
    required: true,
    xs: 12,
    sm: 12,
    md: 12,
  },
  {
    key: generateUniqueKey("email"),
    name: "email",
    label: "Email",
    type: INPUT_TYPES.EMAIL,
    required: true,
    xs: 12,
    sm: 12,
    md: 12,
  },
  {
    key: generateUniqueKey("dateOfBirth"),
    name: "dateOfBirth",
    label: "Date of Birth",
    type: INPUT_TYPES.DATE,
    required: true,
    xs: 12,
    sm: 12,
    md: 12,
  },
  {
    key: generateUniqueKey("salary"),
    name: "salary",
    label: "Salary",
    type: INPUT_TYPES.NUMBER,
    required: true,
    xs: 12,
    sm: 12,
    md: 12,
  },
  {
    key: generateUniqueKey("departmentId"),
    name: "departmentId",
    label: "Department",
    type: INPUT_TYPES.SELECT,
    required: true,
    xs: 12,
    sm: 12,
    md: 12,
  },
];
